config/routes.rb
Rails.application.routes.draw do
  get 'books/index'

  get 'books/edit'

  get 'books/new'

  get 'books/show'

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def edit
  end

  def new
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/home/index.html.erb
home

<h2>Hello developer</h2>

<%= link_to 'Books', books_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>